### ISSUE TITLE
Name 'os' is not defined

### ISSUE THREAD

**Issue by gabrielaaferreira** [stefhk3/nmrfilter#1]
Hello stefhk3! I hope you are doing well. So, I was trying to install the NMR filter on Windows 10 with Anaconda and running it in Jupyter Notebook, but I encountered an issue. I am using the NMR projects that you provided.

![Screenshot_2](https://github.com/stefhk3/nmrfilter/assets/127155266/0d658223-dc85-4b0a-ab88-fd7d0790a010)

**Comment by stefhk3** [comment]
Sorry for late repky. The os module is imported in the first code section (starting with "# Import Dependencies"). Is that one running without errors?

**Comment by gabrielaaferreira** [comment]
Yes, the first module works fine. The second cell has the os command and it selects a project from the folder you offered as an example.
I didn't run the optional cells, maybe that could have been the problem.

**Comment by stefhk3** [comment]
Hm, very strange. right now, the only idea which comes to my mind is to put the "import os" into the code block where it is not found. So before the line "print("clustering the peaks in the measures spectrum...") put a line import os - perhaps that makes a difference. It shouldn't, but I can't see anything here and experimenting then is the only thing which can help.

**Comment by gabrielaaferreira** [comment]
Thank you for the help, but it didn't work out. I also tried import os in the clusterlouvain.py file, no results. Maybe there is something wrong with the directory? I will try to install it in Linux to see what happens.

**Comment by gabrielaaferreira** [comment]
Hi again. So, I tried on Linux, and I encountered the same error. I really don't know what to do.

**Comment by stefhk3** [comment]
could you add "import os" to the clusterlouvain.py file?

**Comment by stefhk3** [comment]
I checked, this should normally not be necessary, but please try. It's the only option I can see now.

**Comment by gabrielaaferreira** [comment]
So I tried to import os after the imports in the clusterlouvain.py and it didn't work. BUT, I tried again to import it on the first line of the archive and IT WORKED! Thank you so much for the help. 
![worked](https://github.com/stefhk3/nmrfilter/assets/127155266/de6efd43-eace-470e-94b4-ac53d59f8986)
